- name: Install base PHP packages
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - php5
    - php5-common
    - php5-cli

- name: Install PHP extensions (modules)
  apt: pkg={{ item.value }}
  sudo: yes
  with_dict: php.modules
  notify: restart-php-webserver

- name: Enable extensions (modules) for all SAPI's
  command: php5enmod -s ALL {{ item.key }}
  sudo: yes
  with_dict: php.modules

- name: Is mysql installed?
  command: which mysql
  register: is_mysql_installed_path

- name: Install php5-mysql extension if mysql installed
  apt: pkg=php5-mysql
  sudo: yes
  when: is_mysql_installed_path | changed
  notify: restart-php-webserver

- name: Enable php5-mysql extension if mysql installed
  command: php5enmod -s ALL mysql
  sudo: yes

- name: Copy PHP settings files
  template:
    src=php.ini.j2
    dest={{ item.value }}
  sudo: yes
  with_dict: php.settings_pathes
  notify: restart-php-webserver
